# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ElectronReact' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ElectronReact

  target 'ElectronReactTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
